# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f271f23b5d5b35ba4a7b0b4848b65b6ed74b0e108b09e2d286c0a5ee0e733fa3b42041ee480766f283bf45b205708a9351b82f3180cf01d6a644e0b9e116c2ed

test:
  secret_key_base: 95110fbbbe30bafe7aaa1f781ea9fc416343dc9598a6f234708320eee266d535367108cab9894baa629509c52ffdcb2d987d329f0a4c9f16302c441f9666f3ee

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
